### ISSUE TITLE
chrome crash when just as soon as it tries to put the password in

### ISSUE THREAD

**Issue by lukebuke34** [LeaDer-E/Tiktok-Auto-Liker#1]
#I hope you like this tool, and it be useful for you to use it, and you can support me at: "www.buymeacoffee.com/LeaDer.E"
login process...
Traceback (most recent call last):
  File "/home/kali/Tiktok-Auto-Liker/LeaDer-E_Liker.py", line 1478, in <module>
    password1 = driver.find_element(By.CSS_SELECTOR, '#loginContainer > div.tiktok-xabtqf-DivLoginContainer.exd0a430 > form > div.tiktok-15iauzg-DivContainer.ewblsjs0 > div > input')
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#loginContainer > div.tiktok-xabtqf-DivLoginContainer.exd0a430 > form > div.tiktok-15iauzg-DivContainer.ewblsjs0 > div > input"}
  (Session info: chrome=103.0.5060.134)
Stacktrace:
#0 0x556cf54dccd3 <unknown>
#1 0x556cf52e4968 <unknown>
#2 0x556cf531bfd7 <unknown>
#3 0x556cf531c1a1 <unknown>
#4 0x556cf534f154 <unknown>
#5 0x556cf5339bdd <unknown>
#6 0x556cf534cea8 <unknown>
#7 0x556cf5339aa3 <unknown>
#8 0x556cf530f3fa <unknown>
#9 0x556cf5310555 <unknown>
#10 0x556cf55242bd <unknown>
#11 0x556cf5528418 <unknown>
#12 0x556cf550e36e <unknown>
#13 0x556cf5529078 <unknown>
#14 0x556cf5502bb0 <unknown>
#15 0x556cf5545d58 <unknown>
#16 0x556cf5545ed8 <unknown>
#17 0x556cf555fcfd <unknown>
#18 0x7fd0458bad80 <unknown>

**Comment by 0xWeverton** [comment]
@lukebuke34 u can change the line `password1 = driver.find_element(By.CSS_SELECTOR, '#loginContainer > div.tiktok-xabtqf-DivLoginContainer.exd0a430 > form > div.tiktok-15iauzg-DivContainer.ewblsjs0 > div > input')` to password1 = driver.find_element(By.XPATH, "//input[@placeholder='Password']")

**Comment by LeaDer-E** [comment]
i thing ther's some thing change at website element, that mean maybe we need to try to create another version of the tool, can u told me if IWSCode Selution is working with you or not

**Comment by graffpro** [comment]
password1 = driver.find_element(By.XPATH, "//input[@Placeholder='Password']")
This code isn`t working for me. Something changed on site
